[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.build]
cmds = ['dotnet restore', 'dotnet publish -c Release -o out']

[start]
cmd = 'dotnet out/OrtosleepApi.dll'

[variables]
DOTNET_CLI_TELEMETRY_OPTOUT = '1'